apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: collect-logs-windows
spec:
  selector:
    matchLabels:
      name: collect-logs-windows
  template:
    metadata:
      labels:
        name: collect-logs-windows
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - image: mcr.microsoft.com/windows/servercore:1809
        name: collect-logs-windows
        volumeMounts:
        - name: ck
          mountPath: "C:/k"
        - name: docker
          mountPath: "C:/Program Files/Docker"
          subPath: "Docker"
        command: ["powershell", "-exec", "bypass", "-c", "(new-object net.webclient).DownloadFile('{{SCRIPT_URL}}', 'C:\\collect-logs.ps1'); C:\\collect-logs.ps1 -ArchivePath C:\\k\\logs.zip"]
        readinessProbe:
          exec:
            command: ["powershell", "-c", "cat", "C:\\k\\collect-logs.done"]
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: ck
        hostPath:
          path: "C:/k"
      - name: docker
        hostPath:
          path: "C:/Program Files"
